### ISSUE TITLE
Add a card component

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-team#1]
## Why we're doing this
Designers need a card component to organize summarized materials, and present these summaries in a scannable, browsable format. A card pattern serves to:
- collect together related materials
- distinguish related collected materials from their context
- connect related collections as a "collection-of-collections"
- provide a simple followup action related to the collected content

The card component is available in [pretty much every design system](https://docs.google.com/spreadsheets/d/1_OQG0I2hlnblwWdIhmtvEFLNgxOvEzb6t2rIHKYPVSc/edit#gid=0):lock: and is a baseline expectation for a design system like USWDS. 

## Related issues and documentation
[Card prototype](https://codepen.io/collection/DOOBJG)
[Problem Statement](https://github.com/uswds/uswds/issues/3148)
[Initial Assumptions and Hypothesis](https://github.com/uswds/uswds/issues/3149)
[Landscape Analysis](https://github.com/uswds/uswds/issues/3161)
[Landscape Analysis of Existing Gov Solutions](https://github.com/uswds/uswds/issues/3162)
[Draft Card Principles](https://github.com/uswds/uswds/wiki/Card-Principles-(Draft))
[Initial build of card component](https://github.com/uswds/uswds/pull/3347)
[Site documentation for the card component](https://github.com/uswds/uswds-site/pull/913)
[`flex-fill` not working in IE11](https://github.com/uswds/uswds/issues/3386)

### Clear
- [ ] Include a well-formed user story, preferably one that connects to research findings
- [ ] Use existing code as much as possible
- [ ] Include only the code necessary for the component
- [ ] Affect as few other components as possible
- [ ] Use USWDS code style
- [ ] Use only USWDS design tokens, mixins, and functions
- [ ] Use the same design patterns to solve the same problems

### Accessible
- [ ] Add component-based tests to automated testing
- [ ] Pass automated CI accessibility review (aXe)
- [ ] Pass semi-automated accessibility review like [Accessibility Insights](https://accessibilityinsights.io/)
- [ ] Pass WCAG 2.1 review
- [ ] Use screen reader and keyboard accessible markup
- [ ] Make scrollable elements focusable for keyboard users
- [ ] Assure markup describes a logical structure/outline

### Resilient
- [ ] Use a mobile-first design methodology
- [ ] Stress-test with edge cases (and document these variants in the library)
- [ ] Outline contexts where this component might appear (and add these templates to the library)
- [ ] Perform critical tasks with low bandwidth and unreliable CSS load
- [ ] Perform critical tasks when JavaScript does not load
- [ ] Document and addresses any new package vulnerability
- [ ] Pass Snyk scan
- [ ] `npm audit`: Contain no Critical vulnerabilities 
- [ ] `npm audit`: Contain no High vulnerability standard dependencies
- [ ] Justify any High vulnerability dev dependencies
- [ ] Provide a print stylesheet
- [ ] Autoprefix with: `"> 2%", "Last 2 versions", "IE 11"`
- [ ] Test back to IE11 with a cross-platform testing tool
- [ ] Include functional unit tests

### Evidence-based
- [ ] Document internal or external developer usability test findings (and link to the documentation)
- [ ] Document internal or external end-user usability test findings (and link to the documentation)
- [ ] Collect links and references to any sources used to create this component in the documentation
- [ ] Perform landscape analysis of existing government examples of the component
- [ ] Compare component features with landscape to assure we're meeting expectations

### Documented
- [ ] Include a guidance page on the [`uswds-site`](https://github.com/uswds/uswds-site) linked to the new [`uswds`](https://github.com/uswds/uswds-site) work branch via `package.json`
- [ ] Include the following sections in site documentation:
  - [ ] Name
  - [ ] Description
  - [ ] Example
  - [ ] Component code
  - [ ] When to use
  - [ ] When to consider something else
  - [ ] Usability guidance
  - [ ] Accessibility guidance
  - [ ] Implementation guidance
  - [ ] When to consider something else
  - [ ] Resources
  - [ ] Package information
- [ ] Document any additions to USWDS settings on the [settings page](https://designsystem.digital.gov/documentation/settings/)
- [ ] Create a [component package](https://designsystem.digital.gov/components/) that allows Sass to import only that component and its dependencies. See [an example](https://github.com/uswds/uswds/blob/develop/src/stylesheets/packages/_usa-search.scss).
- [ ] Use plain language and explain any technical terms
- [ ] Document source code with comments
- [ ] Include a blog post that contextualizes the component work and explains what, why, and how of the component
- [ ] Content proofread with no typos or broken links
