### ISSUE TITLE
Create June Monthly Call Slides and Script

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#166]
# TODO

- [ ] Create slides in Powerpoint
- [ ] Circulate slides for 508 Review
- [ ] Enter 508 remediations
- [ ] Post to Website
- [ ] Post link to Slack
- [ ] Write Script
- [ ] Circulate script for editorial review
- [ ] Highlight URLs
- [ ] Create special terms list
- [ ] Send special terms list to DG
