### ISSUE TITLE
Collect site launches

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#167]
## TODO

- [ ] Collect any new sites to present at monthly call
- [ ] Add that list to the MC prep doc
- [ ] Post the link to the doc in Slack when done
