### ISSUE TITLE
Document the process to get feedback on new components

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#26]
**Background**

As a USWDS customer
I would like to anticipate communication with USWDS on new component releases
So that I can understand the process and contribute feedback throughout

As a USWDS team member
I would like to follow a standard process to receive feedback from customers on new components throughout the lifecycle
So I ensure we're listening and taking customer needs and public user needs into account

This story is about documenting the process to get feedback on new components. We want to understand needs through the lifecycle from discovery to post-release:

* What agency teams need and for what public users
* What they would use the component for
* Existing research or work done by other teams
* Considerations for accessibility and usability
* Any applicable policies, standards, or guidelines that apply, 
* Bugs in using the component
* Share successful implementations
* Further needs for improvements and customization options.

**Acceptance criteria**

- [x] We have documented the process to get feedback on new components
- [x] We have created some boilerplate language to collect feedback at each stage
- [x] We have defined KPIs to measure effectiveness of our efforts to collect feedback
- [x] A folder is created in Google Drive to collect the feedback and research
- [ ] The process is documented and findable in the wiki

**Tasks to complete this issue**
- [x] Define the stages
- [x] Review existing efforts to collect feedback, including from the 10x team
- [x] Draft the high-level process 
- [x] Identify various touchpoints and channels, write boilerplate language, and define KPIs
- [ ] Schedule interviews with a few federal customers
- [x] Analyze feedback and review the process
- [ ] Walk through topline with USWDS lead and validate to-be process
- [ ] Create gDrive folder
- [ ] Post to wiki

**Definition of done**
- [ ]  Acceptance criteria met

**Comment by afeijoo** [comment]
Pick up where https://github.com/uswds/uswds/issues/3424 left off.

**Comment by afeijoo** [comment]
@thisisdano Please take a look at this issue and let us know if it captures everything before we get too far along.

**Comment by jAigret-Bix** [comment]
@afeijoo We have two documents to capture this process. 1. [Lifecycle plan](https://docs.google.com/document/d/1N6lC0svk6gOjcCwQtFsIcJfDg7JfIWqz4vZuc4qBjVA/edit?usp=sharing) documents the process and includes boilerplate language 2. [KPIs: Component Feedback](https://docs.google.com/document/d/17UnhgD8qenxpB4ztWfwQKVpHhLoskPjrLe8_oVxrApE/edit?usp=sharing)

**Comment by afeijoo** [comment]
@jAigret-Bix Thanks, the two documents look good!
