### ISSUE TITLE
Update and validate personas

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#27]
**User story:** 
As a UX specialist, I want to evaluate current personas so that I can either develop new personas and /or revise, validate existing personas. 

This story is about the need to have accurate and updated persona information so that the team can better tailor content and customer experience to specific users of our product. Personas help define common user needs and bring them to the forefront of planning. They provide the team a shared understanding of users in terms of goals and capabilities and help keep our product user focused.

Updated personas will lay the foundation to fulfill product roadmap items such as, but NLT “getting started” content directed at specific users. This information will also inform a larger needs assessment surrounding site IA, content audit, and overall usability. 

[Existing Personas and Roadmap](https://drive.google.com/drive/u/2/folders/0BzXj2nEWSt4IODVvN0c5WDF6UVk)

**Acceptance criteria:** 
- [ ] Documentation of key findings to include recommendations and next steps. What we know, what we need to know.
- [ ] Persona creation/development, revisions, and/or validations. 

**Tasks to complete:** 
- [ ] Synthesize and analyze user research tests, and any other existing information to 
develop key findings and recommendations 
- [ ] Persona creation/development/updates
- [ ] Possible next steps with Katie 

**Definition of Done:** 
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by jAigret-Bix** [comment]
This is a duplicate issue. Work was recorded in  https://github.com/uswds/uswds/issues/3647. Closing this issue
