### ISSUE TITLE
Anchor Component: Discovery

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#28]
**User story:** As a UX specialist, I want to discover user needs surrounding the anchor component so that acceptance criteria for best default is accurate, and so the final component is as valuable as possible. 

This story is linked to the Anchor component epic.  This component is a complement to the footer. Its purpose is to provide a consistent way of presenting information and links that are required by federal policy. The Anchor Component is distinctly different from the footer and has a simple, neutral default. Embedded within the component are best practice suggestions as to what links or information should be included.

**References:** 
USWDS Anchor Issue: https://github.com/uswds/uswds/issues/3525

Previous landscape analysis examples:
https://github.com/uswds/uswds/wiki/Card-Landscape-Analysis
https://bixal.invisionapp.com/freehand/document/tSS644yrC
Previous heuristic analysis (sample: Preliminary analysis: https://github.com/uswds/uswds/wiki/Breadcrumbs-Landscape-Analysis

**Acceptance criteria:** 
-	[x] Research based minimal acceptance criteria for best default and most added value.
-	[x] Landscape Analysis (used to create guidance)
-	[x] Heuristic Analysis (used to create guidance)
-	[x] Naming convention: suggest best practice terminology 
-	[x] Identify users/roles to account for impacts.

**Tasks to complete:**
-	[x] Determine past research techniques. What has been used, what was most useful. 
-	[x] Determine other (or new) platforms for feedback:  Slack, 10x forms, Qualtrics on website.
-	[x] Determine if interviewing users is a useful option? PRA issues (ask Ammie)? Perhaps interview Bixal staff (ask Philip)?
-	[x] Landscape Analysis (used to create guidance)
-	[x] Heuristic Analysis (used to create guidance)
-	[x] Naming convention: suggest best practice terminology 
-	[x] Identify users/roles to account for impacts. Who are key users and what is their specific  information needs? 
-	[x] Determine what is the best default. Define user needs surrounding the default.
-	[x] Develop minimal acceptance criteria for best default and most added value.

**Definition of Done:** 
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by jAigret-Bix** [comment]
Impact with Current Footer Examples (NASA and USDA)
https://bixal.invisionapp.com/d/main?origin=v7#/console/20355423/427201226/preview?scrollOffset=0
 
Footer Visual Competitive Analysis
https://bixal.invisionapp.com/freehand/document/FKDrzhzza
 
Footer Landscape Analysis https://github.com/uswds/uswds/wiki/Footer-Landscape-Analysis
 
Accordion Landscape Analysis https://github.com/uswds/uswds/wiki/Accordion-Landscape-Analysis

**Comment by thisisdano** [comment]
OK, let's move forward with this. 

- It will be the `Anchor` unless a new name can make a better case
- The Anchor should provide a common experience and common information at the bottom of every page of every government website, just as the Banner is at the top of every page of every website. 
- It helps teams make conformance to content requirements simple, by including [all required links](https://digital.gov/resources/required-web-content-and-links/) in a simple consistent presentation
- This helps organizations, by allowing for a simple consistent customizable identification element at the bottom of any web page that can include any necessary logos and necessary shot, descriptive contextual text 
- The Anchor will use a full-width stacked/layered module structure, and allow for possible new modules in future iterations
- It will include an action-oriented link to USA.gov as a distinct module at the very bottom of every page
- The required links module will be full-width and include all links in a compact view that is visible without an accordion, directly above the USA.gov module
- It will include an optional module at the top for agency/product identification
- The identification module is meant to include logos and short descriptive text
- Once we have a solid content model, we'll test the Anchor with multiple languages to assure resilience
- Similarly to the Banner, most of the text in the Anchor is not meant to be editable. The exception is the identification module.

Did I miss anything?

Let's include all landscape analysis and initial sketch links in our internal documentation, then we can close this issue.

cc @jAigret-Bix @allie-shaw @katieekline @mejiaj
