### ISSUE TITLE
Standardize Issue Criteria

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#29]
**User story:** As a PM, I want to standardize issue criteria, so that issues are detailed, clear and understandable to the entire team.  

This story will create consistency across issues.

**Acceptance criteria:** 
-	[ ] Approved documentation of issue criteria guidance
-	[ ]  Archived to appropriate location for ease of reference

**Tasks to complete:**
-	[ ] Research past issues for good examples 
-	[ ]  Develop issue criteria
-	[ ]  Is there an existing template for guidance and SOP documentation?
-	[ ]  Submit for feedback and revisions and Approval

**Definition of Done:** 
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by afeijoo** [comment]
@thisisdano A draft gDoc with the [issue criteria](https://drive.google.com/file/d/1EbVSdPbxODDWP3b6F22cYm00COy2nRD5/view?usp=sharing):lock: is ready for your review.

**Comment by thisisdano** [comment]
Re-saved as a gDoc and reformatted, edited, etc. This seems good as a draft — do we expect any more work on it before calling it done?

**Comment by jAigret-Bix** [comment]
I don't have any further edits on my end. [Located here](https://drive.google.com/drive/u/2/folders/1EMtdlRLZzRyi764giS2xMwkb5MHgJrxb)
Ready for issue completion.

**Comment by thisisdano** [comment]
LGTM. :shipit:
