### ISSUE TITLE
USWDS-team - Feature request: Create an issue template for recurring events

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-team#296]
Create an issue template to more easily and consistently track recurring events, like Monthly Call and Newsletter.

**Required issue templates**

- Monthly Call
- Newsletter
- ~POAM~ This can be a follow-up.

**Definition of done**

- [ ] Outline tasks for each event
- [ ] Create basic description
- [ ] Create a task list
- [ ] Create GDoc of process
## Additional context

We can start with these and create more templates as we identify other recurring events.

## References

- [Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [Scheduling issues (_Alternatively we could try scheduling these issues_)](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation)

**Comment by mejiaj** [comment]
@sarah-sch @katieekline can you add an outline of basic tasks for the newsletter? We can start there.

**Comment by finekatie** [comment]
Hey @sarah-sch ,  is this something we create as a doc, in a spreadsheet or as a template for tickets going forward?

**Comment by sarah-sch** [comment]
@finekatie I think what James had in mind was a an issue template in GitHub -- but docs and spreadsheets could also be helpful for organizing these tasks! I'm going to add @brunerae to this issue because I think she might be best suited to handling the monthly call portion. (Ashley, I don't want to presume, so if you would rather we take the lead on MC issues please do say so!)

**Comment by ryparker** [comment]
Closing during the approved September 2026 backlog consolidation.

Monthly-call/newsletter templates assume an events program that is not part of the stated operating model. A release checklist can cover necessary consumer communication.
