### ISSUE TITLE
Improve Issue Management

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#30]
**User story:** As a PM, I want to guide and streamline the issue management process so that our team is working smoothly in an agile framework. 

This story will help to create consistency with the agile methodology and provide guidance as to where, when, and how work is tracked.

**Acceptance criteria:** 
-	[ ] Approved documentation of issue management guidance
-	[ ] Archived to appropriate location for ease of reference
-	[ ] Plan for a revisit and revision for continued improvement

**Tasks to Complete:** 
-	[ ] Research current agile process and determine issues and improvements
-	[ ] Research current issue content process
-	[ ] Research best way to treat epics, stories, tasks, subtasks with in Github. 
-	[ ] Determine best options on how to measure LOE
-	[ ] Submit documentation for feedback and revisions

**Definition of Done:** 
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by afeijoo** [comment]
@thisisdano A draft gDoc with the [agile management processes](https://drive.google.com/file/d/1kwnR4ZQg7GFMnhxKoo1zCSgSSsDOVvmY/view?usp=sharing):lock: is ready for your review.

**Comment by thisisdano** [comment]
Converted this from word to gDoc and made a few edits and comments: https://docs.google.com/document/d/1L6-5BVhsKVd_B1pzB0NjYZCsGrrPSKEA4aP88JyY3rA/edit?usp=sharing

**Comment by jAigret-Bix** [comment]
@thisisdano  [Final doc here](https://docs.google.com/document/d/1L6-5BVhsKVd_B1pzB0NjYZCsGrrPSKEA4aP88JyY3rA/edit?usp=sharing). I want to begin to work in sprint retros and revisit this in a couple weeks. I think this is a good starting point for documentation.
