### ISSUE TITLE
December 2023 Newsletter

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#302]
Create and publish [December 2023 Newsletter](link TBA). 
Deadline for publish: 12/11

Helpful links:

- [Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
- [GovDelivery](https://admin.govdelivery.com/session/new)

### To-Do
- [ ] Draft copy
- [ ]   Make sure release notes are available to link to
- [ ]   Write summary of release for newsletter
- [ ]   New USWDS websites 
- [ ]   Other content as needed (ask team if previously mentioned content items are sparse)  
- [ ]   Important issues or announcements (will come to us from Anne/Dan, as determined)
- [ ] Get feedback from content team
- [ ] Get feedback from larger team - it can be especially helpful to to have the dev team review your edits to their release notes copy if you are unsure that we're getting the technical details right
- [ ] Approval: Anne and Dan
- [ ] Add content to GovDelivery
- [ ] Proofread
