### ISSUE TITLE
Anchor Component (Milestone)

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#32]
**Description:** Anchor component is a complement to the footer. Its purpose is to provide a consistent way of presenting information and links that are required by federal policy. The Anchor Component is distinctly different from the footer.  It has a simple, neutral default. Embedded within the component are best practice suggestions as to what links or information should be included.

**Value:** will add some nice consistency to how agencies link back to USA.gov. 
Making the requirement that states that all gov sites need to link to USA.gov "official" in the USWSDS (with consistent language in both, English and Spanish) is fantastic. Other gov agencies won't have to worry about where exactly to put it, the verbiage and the style.

**Issue info:** This component has previously been developed by digital.gov. The Bixal team should complete discovery process to validate digital.gov or further develop a new prototype or new features.
Example: https://digital.gov/
Digital.gov Issue: https://github.com/GSA/digitalgov.gov/issues/2351
USWDS Issue: https://github.com/uswds/uswds/issues/3525

**Acceptance Criteria**
- [x] All associated tasks and issues are complete:

-	[x] Discovery - https://github.com/uswds/uswds-team/issues/28 
-	[x] Wireframe/Prototype -  https://github.com/uswds/uswds/issues/3565
-	[x] Content
-	[x] Build
-	[x] Test
-	[x] Release

**Definition of Done:** 
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by jAigret-Bix** [comment]
https://github.com/orgs/uswds/projects/4#card-35974081 roadmap card can be moved to Done. Re-named "Identifier" released September 2020, v2.9.0
