### ISSUE TITLE
USWDS-Team - Component lifecycle: Create demo proposal repo

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-team#333]
## Summary
Create a demo proposal repo that includes a proposal template, README, and labels. This will be an area to experiment before moving the repo into the uswds org in https://github.com/uswds/uswds-team/issues/334.

### Tasks
- Explain steps and provide instructions 
- Create proposal template 
- Create README
- Create list of repo labels

### Deliverables
- [ ] README with instructions
    - Related issue: https://github.com/uswds/uswds-team/issues/331
- [ ] Proposal template with instructions for each item
    - Related issue: https://github.com/uswds/uswds-team/issues/332
- [ ] List of proposed labels 
    - Related doc: [Proposal repo labels](https://docs.google.com/document/d/1KKCj5qSsHWgh0X00JlxW_OCSFXAbGO88o2wnIbdebng/edit#heading=h.fa3sv1ray42g) (Google Doc :lock:)

## Work in progress
- [Demo proposal repo](https://github.com/amyleadem/uswds-proposals/pull/1) (GitHub)

## Related work
- [Component lifecycle documents in Google Drive](https://drive.google.com/drive/folders/14EBpWLlWr3EaEeLF5JF-Tii9WyUpez6y) ( :lock:)

**Comment by brunerae** [comment]
Decision per 2/6 Component Lifecycle Proposals working session: we'll use Discussions to capture proposals. 

See [notes in Google Drive](https://docs.google.com/document/d/1vpk0SSrsWQF22GkNNHKDzO3WjE2A_5WXO4VZ9oQxx78/edit#heading=h.fa3sv1ray42g) (🔒)

**Comment by amyleadem** [comment]
Closing as complete
