### ISSUE TITLE
August Monthly Call (8.20) // Follow up items

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#37]
August Monthly Call (8.20) fairly light due to outside presenter
Topics:
	• 2.8.1 release review
	• Any new site launches
Tasks:
	• Pre activities: script submission and review
• Prep // run through meeting
• post activities (blogs, etc) 

**Tasks:**
- [X] Meeting to determine what to share. Scheduled 8.26.
- [X] Schedule a reoccurring 30-min post call recap from 3:40-4 pm ET (Dan, Ammie, Jaimee, Katie, Allie goal: collect links and high level recap in post)
- [x] @katieekline to develop [post call gDoc for review](https://docs.google.com/document/d/1wIWor37Izc3TgfTv8QDKxf_5r2Ic1xPhNfIA9xIWFG8/edit#heading=h.p3hvn8jllvv2)
- [x] Approval of message by client 
- [x] Share a recap of the call with links to a key resource or two in #uswds-public.

**Comment by katieekline** [comment]
@afeijoo and @thisisdano The [draft Slack post](https://docs.google.com/document/d/1wIWor37Izc3TgfTv8QDKxf_5r2Ic1xPhNfIA9xIWFG8/edit?usp=sharing) is ready for your review.

**Comment by nks-bix** [comment]
@thisisdano please review @katieekline 's [draft slack post](https://docs.google.com/document/d/1wIWor37Izc3TgfTv8QDKxf_5r2Ic1xPhNfIA9xIWFG8/edit?usp=sharing) when you get a chance.  If it's good to go, let's post it!

**Comment by thisisdano** [comment]
OK, I've finished up feedback and approval

**Comment by jAigret-Bix** [comment]
@katieekline approved and ready to go out to uswds-public

**Comment by jAigret-Bix** [comment]
Slack Post[https://gsa-tts.slack.com/archives/C3F14AHSQ/p1599671575056300](url)
@thisisdano  Issue can be closed
