### ISSUE TITLE
POAM - July '24

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-team#370]
# Summary

POAM for July 2024

> [!NOTE]
> Updating Compile will resolve many vulnerabilities in the repos that use it. If possible, we should include these updates with this POAM.

- [ ] uswds/uswds#5972
- [ ] uswds/uswds-site#2745 _// Waiting for compile updates_
- [x] Compile
  - [x] uswds/uswds-compile#109
  - [x] uswds/uswds-compile#96
  - [x] https://github.com/uswds/uswds-compile/pull/103
- [ ] uswds/uswds-sandbox#144 // Waiting for compile updates.
- [x] uswds/uswds-tutorial#54
- [ ] uswds/public-sans#306
- [x] USWDS-Next _// No changes_

**Comment by mahoneycm** [comment]
Closing in favor of #379
