### ISSUE TITLE
USWDS - POAM: August '24

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-team#379]
# Summary

POAM for July 2024

> [!NOTE]
> Updating Compile will resolve many vulnerabilities in the repos that use it. If possible, we should include these updates with this POAM.

- [x] uswds/uswds#5972
- [x] USWDS-Site
  - uswds/uswds-site#2745
  - uswds/uswds-site#2605
- [x] uswds/uswds-compile#112
- [x] uswds/uswds-next#43
- [x] uswds/uswds-sandbox#144
- [x] uswds/uswds-tutorial#56
- [x] uswds/public-sans#306

**Comment by thisisdano** [comment]
All done, thanks!
