### ISSUE TITLE
QA spotlight data and re-run site scanner

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#40]
Update and validate site scanner information

**Tasks**
- [x] QA spotlight data from August
- [x] re-run site scanner
- [x] QA updated spotlight data from September

**AC**
- [x] Tasks complete

**Comment by afeijoo** [comment]
@jAigret-Bix I reran the site scanner and added a `To check` tab for September. The next step is to QA the updated data.
