### ISSUE TITLE
Modernize USWDS Websites (epic)

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#7]
## Why we're doing this

All GSA websites must follow the [Guidelines for GSA’s Digital Presence](https://docs.google.com/document/d/1E0K_LDlDqEgHKESTqHKlKN50OJAxCcl_FcKB-qLL13A/edit#heading=h.p589tnu6y5e0):lock: linked within [GSA Order 2140.2](https://insite.gsa.gov/directives-library/management-of-gsas-digital-presence-21402-osc):lock:. GSA also developed [compliance criteria](https://docs.google.com/document/d/1p2ufP5cgkK1RMepUKQ6OLKYfH8GRa26-ma7vUODk6gE/edit):lock: to help web managers follow these guidelines and meet the goals of [21st Century IDEA](https://digital.gov/resources/21st-century-integrated-digital-experience-act/). 

All GSA sites were required to have a modernization plan in place by May 2020. Below are the action items from the website modernization plans for USWDS websites.

## designsystem.digital.gov

In FY 2020, based on the [Modernization Plan for designsystem.digital.gov](https://docs.google.com/spreadsheets/d/1mXyxlx3JjqrY2Ct5GuTNqO_NbUFucD7Jj2DLn7ysdys/edit):lock:, we will make the following improvements on https://designsystem.digital.gov:

- [ ] https://github.com/uswds/uswds/issues/3733 incorporate more a11y testing (est. 40 hours)
- [x] https://github.com/uswds/uswds-site/pull/1046 to add `Identifer` that follows GSA branding guidelines (est. 0-100 hours)
- [x] https://github.com/uswds/uswds-site/pull/1046 to add `Identifer` with the required links 
- [x] Update link notifications (est. 10-20 hours)

## components.designsystem.digital.gov

In FY 2020, based on the [Modernization Plan for components.designsystem.digital.gov](https://docs.google.com/spreadsheets/d/1pnTu5fESTGpp1PaFoDwoIoPLwFv5dy9ruGjz1mbsCpU/edit):lock:, we will make the following improvements on https://components.designsystem.digital.gov:

~- [ ] Incorporate a11y testing (est. 40 hours)~
~- [ ] Use USWDS, follow GSA branding guidelines, and add anchor (est. 40 hours)~
~- [ ] Add DAP~
~- [ ] Add USWDS GA~

- [x] https://github.com/uswds/uswds/issues/3644 to decommission https://components.designsystem.digital.gov

## public-sans.digital.gov

In FY 2020, based on the [Modernization Plan for public-sans.digital.gov](https://docs.google.com/spreadsheets/d/1s4CYkZqSmn04a_BK94eyfYZ9iRSSoLfn7AY8xsMfpEw/edit):lock:, we will make the following improvements on https://public-sans.digital.gov:

- [ ] https://github.com/uswds/uswds/issues/3734 to incorporate a11y testing (est. 10-20 hours)
- [x] https://github.com/uswds/uswds-site/issues/1067 to follow GSA branding guidelines (est. 10-20 hours)

## v1.designsystem.digital.gov ✅ 

In FY 2020, based on the [Modernization Plan for v1.designsystem.digital.gov](https://docs.google.com/spreadsheets/d/1YkKX8eyO2YkH992GSqt_syib9Hd_fRQ8_hadA0PT3ts/edit):lock:, we will make the following improvement on https://v1.designsystem.digital.gov:

- [x] https://github.com/uswds/uswds-site/issues/940 to add banner to clarify it is an archived site (est. 5-10 hours)

## v2alt.designsystem.digital.gov ✅ 

- [x] https://github.com/18F/dns/issues/427 to decommission https://v2alt.designsystem.digital.gov/ (currently returns a 404); closed by https://github.com/18F/dns/pull/450 and https://github.com/18F/dns/pull/453

## Redirects
We will continue to maintain redirects for four legacy subdomains: 

1. https://components.standards.usa.gov
1. https://design-principles-guide.18f.gov
1. https://standards.usa.gov
1. https://v2.designsystem.digital.gov

**Comment by afeijoo** [comment]
Archive banner is now on https://v1.designsystem.digital.gov/. See https://github.com/uswds/uswds-site/issues/940

**Comment by afeijoo** [comment]
v2alt.designsystem.digital.gov is now decommissioned. Closed by https://github.com/18F/dns/pull/450.

**Comment by afeijoo** [comment]
Identifier with required links and GSA branding is now on https://designsystem.digital.gov/. See https://github.com/uswds/uswds-site/pull/1046, which updates the site to USWDS 2.9.0.

**Comment by afeijoo** [comment]
Done. https://components.designsystem.digital.gov now redirects to https://designsystem.digital.gov/components

https://github.com/18F/pages-redirects/pull/170 and https://github.com/18F/dns/pull/495
